# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

platform :mac do
  before_all do
    setup_circle_ci
  end

  desc "Push a new release build to the App Store"
  lane :release do
    build_app(scheme: "App macOS", clean: true)
    upload_to_app_store(
      api_key_path: "fastlane/ApiKey.json",
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
      submit_for_review: true,
      submission_information: {
        export_compliance_uses_encryption: false,
        add_id_info_uses_idfa: false
      }
    )
  end
end


platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Push a new release build to the App Store"
  lane :release do
    build_app(scheme: "App iOS", clean: true)
    upload_to_app_store(
      api_key_path: "fastlane/ApiKey.json",
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
      submit_for_review: true,
      submission_information: {
        export_compliance_uses_encryption: false,
        add_id_info_uses_idfa: false
      }
    )
  end
end
